// Localhost Test

### Get all contacts
GET http://localhost:8080/contacts

### Get by ID
GET http://localhost:8080/contacts/65ac69f8c9928e61c47be0e3
###
GET http://localhost:8080/contacts/65ac69f8c9928e61c47be0e2
###
GET http://localhost:8080/contacts/65ac69f8c9928e61c47be0e1
###
GET http://localhost:8080/contacts/65b315d155960690ee55e7b0

### Create new contact
POST http://localhost:8080/contacts
Content-Type: application/json

{
    "firstName": "Nick",
    "lastName": "Yang",
    "email": "nickyang@email.com",
    "favoriteColor": "Green",
    "birthday": "10/09/00" 
}

### Update contact
PUT http://localhost:8080/contacts/65b315d155960690ee55e7b0
Content-Type: application/json

{
    "firstName": "Nick",
    "lastName": "Yang",
    "email": "nickyang@email.com",
    "favoriteColor": "Red",
    "birthday": "10/09/00" 
}

### Delete contact
DELETE http://localhost:8080/contacts/65b329573427cc822e5de37a
Content-Type: application/json

// Production Test 

### Get all contacts
GET https://connect-mongodb.onrender.com/contacts

### Get by ID
GET https://connect-mongodb.onrender.com/contacts/65ac69f8c9928e61c47be0e3
###
GET https://connect-mongodb.onrender.com/contacts/65ac69f8c9928e61c47be0e2
###
GET https://connect-mongodb.onrender.com/contacts/65ac69f8c9928e61c47be0e1

### Create new contact
POST https://connect-mongodb.onrender.com/contacts
Content-Type: application/json

{
    "firstName": "Nick",
    "lastName": "Yang",
    "email": "nickyang@email.com",
    "favoriteColor": "Red",
    "birthday": "10/09/00" 
}

### Update contact
PUT https://connect-mongodb.onrender.com/contacts/65b333d226fc274459febfc3
Content-Type: application/json

{
    "firstName": "Nicolai",
    "lastName": "Yang",
    "email": "nickyang@email.com",
    "favoriteColor": "Green",
    "birthday": "10/09/00" 
}

### Delete contact
DELETE https://connect-mongodb.onrender.com/contacts/65b333d226fc274459febfc3
Content-Type: application/json
